#! /usr/bin/env bash
ROOT_DIR="$(dirname $0)/../"
INPUT_FILE="${ROOT_DIR}/test/fixtures/01.txt"
source $(dirname $0)/functions.inc
RUNCMD=$(runcmd 01)
BLOCK=0

testBlock() {
  assertEquals 1 $(block 0 | wc -l)
  assertEquals 1 $(block 1 | wc -l)
  assertEquals 2 $(block -1 | wc -l)
}

testBlockCount() {
  assertEquals 2 $(block_count)
}

testBlockOrder() {
  assertEquals "2 1" "$(block_order -1)"
  assertEquals "1" "$(block_order 0)"
  assertEquals "1" "$(block_order 1)"
}

testLines() {
  assertEquals 2 $(${RUNCMD} | wc -l)
}

testSortLine1() {
  assertEquals 1 "$(${RUNCMD} | sed '1!d')"
}

testSortLine2() {
  assertEquals 2 "$(${RUNCMD} | sed '2!d')"
}

# Load shUnit2.
source $(dirname $0)/shunit/shunit2
