#! /usr/bin/env bash
source $(dirname $0)/functions.inc
RUNCMD=$(runcmd 01)
BLOCK=0

testLines() {
  assertEquals 2 $(${RUNCMD} | wc -l)
}

testSortLine1() {
  assertEquals 1 "$(${RUNCMD} | sed '1!d')"
}

testSortLine2() {
  assertEquals 2 "$(${RUNCMD} | sed '2!d')"
}

# Load shUnit2.
source $(dirname $0)/shunit/shunit2
