#! /usr/bin/env bash
source $(dirname $0)/functions.inc
RUNCMD=$(runcmd 01)

testLines() {
  assertEquals $(${RUNCMD} | wc -l) 2
}

testSortHead() {
  assertEquals $(${RUNCMD} | head -n1) 1
}

testSortTail() {
  assertEquals $(${RUNCMD} | tail -n1) 2
}

# Load shUnit2.
source $(dirname $0)/shunit/shunit2
