#! /usr/bin/env bash
ROOT_DIR="$(dirname $0)/../"
INPUT_FILE="${ROOT_DIR}/test/fixtures/02.txt"
source $(dirname $0)/functions.inc
RUNCMD=$(runcmd 01)
BLOCK=0

testBlockCount() {
  assertEquals 2 $(block_count)
}

testBlockOrder() {
  assertEquals "2 1" "$(block_order)"
}

testLines() {
  assertEquals 6 $(${RUNCMD} | wc -l)
}

testBlock0Lines() {
  assertEquals 3 $(${RUNCMD} 0 | wc -l)
}

testBlock0Key() {
  assertEquals "1:" "$(${RUNCMD} 0 | sed '1!d')"
}

testBlock0Line2() {
  assertEquals "first" $(${RUNCMD} 0 | sed '2!d')
}

testBlockLine2() {
  assertEquals "second" $(${RUNCMD} 0 | sed '3!d')
}

# Load shUnit2.
source $(dirname $0)/shunit/shunit2
