#! /usr/bin/env bash
source $(dirname $0)/../lib/shell_functions.inc

testBlockCount() {
  assertEquals 2 $(${RUNCMD} | wc -l)
}

testSortLine1() {
  assertEquals 1 "$(${RUNCMD} | sed '1!d')"
}

testSortLine2() {
  assertEquals 2 "$(${RUNCMD} | sed '2!d')"
}

# Load shUnit2.
source $(dirname $0)/shunit/shunit2
